---
- name: Install NHC for RedHat
  ansible.builtin.include_tasks: rhel-install.yml
  when: ansible_os_family == "RedHat"

- name: Install NHC for Suse
  ansible.builtin.include_tasks: suse-install.yml
  when: ansible_os_family == "Suse"

- name: Configure NHC
  ansible.builtin.import_tasks: configure.yml
